# Generated by Django 2.1.3 on 2018-12-12 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('manaCost', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('cmc', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('flavor', models.CharField(max_length=1000)),
                ('imgUrl', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Deck'),
        ),
    ]
