# Generated by Django 2.1.3 on 2018-12-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=150)),
                ('mana_cost', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('flavor', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Player'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_deck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builder.Deck'),
        ),
    ]
