# Generated by Django 2.1.3 on 2018-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='mana_cost',
            new_name='cmc',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='flavor',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_deck_id',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck_player',
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='builder.Card'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
