# Generated by Django 2.1.3 on 2018-12-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20181211_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='flavor',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
