# Generated by Django 2.1.3 on 2018-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20181214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
