# Generated by Django 2.1.3 on 2018-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20181210_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
