# Generated by Django 2.1.3 on 2018-12-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_player_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='flavor',
            new_name='bio',
        ),
    ]
