# Generated by Django 2.1.3 on 2018-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
