# Generated by Django 2.1.3 on 2018-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20181211_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imgUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
